# Generated by Django 6.0.6 on 2026-06-17 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
    ]
