# Generated by Django 6.0.6 on 2026-07-03 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_auto_20260617_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='asistencia',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='promedio',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='proyectos_hechos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='proyectos_totales',
            field=models.IntegerField(default=15),
        ),
    ]
