# Generated by Django 6.0.6 on 2026-07-03 06:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_estudiante_asistencia_estudiante_promedio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='asistencia',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='promedio',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)]),
        ),
    ]
