# Generated by Django 6.0.6 on 2026-08-18 02:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_alter_estudiante_asistencia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entregable',
            name='fecha_entrega',
        ),
        migrations.AddField(
            model_name='entregable',
            name='cantidad_entregados',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='entregable',
            name='fecha_publicacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entregable',
            name='fecha_vencimiento',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
