# Generated by Django 6.0.6 on 2026-08-18 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_remove_entregable_fecha_entrega_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entregable',
            name='entregado',
        ),
    ]
