# Generated by Django 6.0.6 on 2026-08-18 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_remove_entregable_entregado'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregable',
            name='estudiantes',
            field=models.ManyToManyField(blank=True, related_name='entregables_completados', to='myApp.estudiante'),
        ),
    ]
