# Generated by Django 6.0.6 on 2026-09-09 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0010_registroasistencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregable',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='entregables/'),
        ),
        migrations.AddField(
            model_name='entregable',
            name='consigna',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='entregable',
            name='publicado',
            field=models.BooleanField(default=True),
        ),
    ]
