# Generated by Django 6.0.6 on 2026-09-09 02:40

import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone


def copiar_entregas_desde_m2m(apps, schema_editor):
    Entregable = apps.get_model('myApp', 'Entregable')
    Entrega = apps.get_model('myApp', 'Entrega')
    for entregable in Entregable.objects.all():
        fecha = entregable.fecha_publicacion or timezone.now()
        for estudiante in entregable.estudiantes.all():
            Entrega.objects.get_or_create(
                entregable=entregable,
                estudiante=estudiante,
                defaults={'fecha_entrega': fecha},
            )


def revertir(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0011_entregable_archivo_entregable_consigna_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrega', models.DateTimeField(null=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='entregas/')),
                ('entregable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='myApp.entregable')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='myApp.estudiante')),
            ],
            options={
                'unique_together': {('entregable', 'estudiante')},
            },
        ),
        migrations.RunPython(copiar_entregas_desde_m2m, revertir),
        migrations.AlterField(
            model_name='entrega',
            name='fecha_entrega',
            field=models.DateTimeField(),
        ),
        migrations.RemoveField(
            model_name='entregable',
            name='estudiantes',
        ),
    ]
