# Generated by Django 6.0.6 on 2026-09-09 02:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0012_remove_entregable_estudiantes_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='observaciones',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('entregable', 'Entregable'), ('participacion', 'Participación'), ('evaluacion', 'Evaluación')], default='entregable', max_length=20)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('nota', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('observaciones', models.CharField(blank=True, default='', max_length=255)),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='myApp.inscripcion')),
            ],
        ),
    ]
