# Generated by Django 6.0.6 on 2026-09-09 03:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0013_inscripcion_observaciones_nota'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrega',
            name='nota',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(10.0)]),
        ),
        migrations.AddField(
            model_name='nota',
            name='entrega',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nota_academica', to='myApp.entrega'),
        ),
    ]
