# Generated by Django 6.1 on 2026-09-14 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0015_estudiante_user_resena'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='documento',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Documento'),
        ),
    ]
