# Generated by Django 6.0.6 on 2026-09-15 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0016_estudiante_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='cursos/portadas/', verbose_name='Imagen de portada'),
        ),
    ]
