# Generated by Django 6.0.6 on 2026-09-15 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0017_curso_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesor',
            name='profesion',
        ),
    ]
