# Generated by Django 6.1 on 2026-09-22 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0018_remove_profesor_profesion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='imagen',
        ),
        migrations.AddField(
            model_name='profesor',
            name='profesion',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='documento',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Documento'),
        ),
    ]
