# Generated by Django 6.1 on 2026-09-22 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0019_remove_curso_imagen_profesor_profesion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to='cursos/portadas/'),
        ),
    ]
